# nesse exemplo simples, ao inicializar contêiner
# vai dizer: "olá, mundo!"

# no terminal, vamos criar imagem
# docker build -t nomeImagem

# no terminal, vamos exercuta o contêiner
# docker run  nomeImage

FROM debian

CMD ["echo", "Olá, mundo!"]