version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /caminho/do/seu/certificado:/etc/nginx/certs:ro  # Substitua pelo caminho dos seus certificados
