version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:443"
      - "443:443"
    volumes:
      - wp_files:/usr/share/nginx/html
      - ./volumes/nginx_certs:/etc/nginx/certs
    networks:
      - wordpress_network
    restart: always

  wordpress:
    build:
      context: ./wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wp_files:/usr/share/nginx/html
    networks:
      - wordpress_network
    restart: always

  mariadb:
    build:
      context: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - ./volumes/wp_db:/var/lib/mysql
    networks:
      - wordpress_network
    restart: always

networks:
  wordpress_network:
    driver: bridge

volumes:
  wp_files:
  wp_db:
